-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Gazdă: 127.0.0.1
-- Timp de generare: iun. 19, 2023 la 07:36 AM
-- Versiune server: 10.4.27-MariaDB
-- Versiune PHP: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Bază de date: `zoo`
--

-- --------------------------------------------------------

--
-- Structură tabel pentru tabel `animals`
--

CREATE TABLE `animals` (
  `id` int(11) NOT NULL,
  `animalid` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `science_name` varchar(50) NOT NULL,
  `type` varchar(20) NOT NULL,
  `region` varchar(50) NOT NULL,
  `climate` varchar(20) NOT NULL,
  `conservation_status` varchar(50) NOT NULL,
  `description` varchar(2000) NOT NULL,
  `min_weight` int(11) NOT NULL,
  `max_weight` int(11) NOT NULL,
  `date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Eliminarea datelor din tabel `animals`
--

INSERT INTO `animals` (`id`, `animalid`, `name`, `science_name`, `type`, `region`, `climate`, `conservation_status`, `description`, `min_weight`, `max_weight`, `date`) VALUES
(1, 1, 'Lion', 'Panthera leo', 'Mammal', 'Africa', 'Savannah', 'Endangered', 'Lions are large and powerful carnivores known for their majestic appearance and distinctive manes. Lions (scientifically known as Panthera leo) are the only truly social cats, living in family groups called prides. Adult males are easily recognized by their impressive manes, which vary in color and length. They have a muscular and compact body, females being slightly smaller. Lions have a sandy or tawny coat, providing camouflage in their savanna and grassland habitats. They are highly specialized predators with sharp retractable claws, strong jaws, and formidable teeth. \r\nLions are primarily active during the cooler hours of the day, often engaging in cooperative hunting strategies to take down large ungulate prey such as zebras, wildebeests, and buffalo. However, they are opportunistic and will scavenge or prey on smaller animals when necessary.', 150, 250, '2023-06-13 22:15:00'),
(3, 2, 'Green Python', 'Morelia viridis', 'Reptile', 'Australia', 'Rainforest', 'Least Concern', 'The Green Python (Morelia viridis), also known as the Green Tree Python, is a species of non-venomous snake found in the tropical rainforests of northern Australia and Papua New Guinea. It is known for its striking emerald-green coloration, which provides excellent camouflage in the lush green foliage of its habitat. The snake has a slender body with a slightly flattened head and eyes that have vertical pupils.\r\n\r\nThe Green Python exhibits sexual dimorphism, with females generally being larger and heavier than males. On average, adult males typically weigh between 1 to 1.5 kilograms, while adult females can reach weights ranging from 1.5 to 2.5 kilograms.\r\nIt\'s important to note that individual snakes can exhibit some variation in size and weight, and exceptional individuals may exceed these average ranges. These weight ranges provide a general idea of the size and weight characteristics of the Green Python species.', 1, 3, '2023-06-16 22:27:12'),
(4, 3, 'Zebra', 'Equus quagga', 'Mammal', 'Africa', 'Savannah', 'Least Concern', 'Zebras have a distinctive black and white striped coat pattern. The stripes are vertical on the head, neck, and upper body, and become horizontal on the hindquarters and legs. Each individual has a unique pattern of stripes, which can be used for identification. The stripes are thought to serve as a form of camouflage, confusing predators and helping zebras blend into a group.\r\n Zebras are highly social animals and live in small to large herds. These herds are usually led by a dominant stallion, or male zebra, who protects the group from predators and helps to maintain social order. Female zebras and their offspring form the core of the herd. Zebras communicate with each other through vocalizations, body postures, and facial expressions.', 200, 450, '2023-06-14 18:28:43'),
(7, 5, 'Bald Eagle', 'Haliaeetus leucocephalus', 'Bird', 'North America', 'Temperate', 'Least Concern', 'The Bald Eagle is a majestic bird of prey and the national bird and symbol of the United States. With its distinctive white head and tail, contrasting dark brown body, and impressive wingspan of up to 2.3 meters (7.5 feet), it is easily recognizable. Found primarily in North America, the Bald Eagle inhabits diverse environments such as forests, coasts, and lakeshores. It is a skilled hunter, feeding primarily on fish but also preying on small mammals and waterfowl. As a conservation success story, the Bald Eagle population has rebounded from the brink of extinction and is currently listed as Least Concern on the conservation status scale.', 3, 7, '2023-06-18 16:27:02'),
(8, 6, 'White Shark', 'Carcharodon carcharias', 'Fish', 'Asia', 'Temperate', 'Vulnerable', 'The White Shark, scientifically known as Carcharodon carcharias, is an iconic and powerful apex predator that inhabits coastal and offshore waters around the world. It is characterized by its large, torpedo-shaped body, dark gray or brownish upper body, and distinctive white underbelly. The White Shark is known for its formidable size and strength, capable of reaching lengths of over 6 meters (20 feet). With rows of serrated teeth, it feeds primarily on marine mammals, such as seals and sea lions, as well as fish and carrion. Despite its fearsome reputation, the White Shark is a vital part of marine ecosystems. However, due to overfishing, habitat degradation, and accidental capture, it is listed as a vulnerable species on the conservation status scale. Conservation efforts are crucial to ensure the protection and survival of this magnificent and important marine predator.', 680, 2268, '2023-06-18 16:47:34'),
(9, 7, 'Arctic Fox', 'Vulpes lagopus', 'Mammal', 'Circumpolar', 'Arctic tundra', 'Least Concern', 'Arctic Foxes are known for their stunning white fur in winter, which helps camouflage them in the snowy landscape, and their brown or grayish fur in summer, allowing them to blend into the tundra environment. They have a compact body with a bushy tail, which they use for balance and warmth. These foxes are opportunistic predators and scavengers, feeding on small mammals, birds, fish, carrion, and even insects and berries when available.\r\n\r\nTheir ability to withstand the extreme cold and adapt to the unique Arctic environment makes the Arctic Fox a remarkable species of the far north.', 3, 7, '2023-06-18 18:10:52'),
(10, 8, 'Brown Bear', 'Ursus arctos', 'Mammal', 'Europe', 'Temperate', 'Least Concern', 'The Brown Bear, scientifically known as Ursus arctos, is a large and powerful mammal that inhabits various regions of the Northern Hemisphere. It is characterized by its robust body, shaggy fur, and a distinctive hump of muscle on its shoulders. Brown Bears exhibit a wide range of sizes, with adult males being significantly larger than females. They have an omnivorous diet, feeding on a variety of foods including berries, nuts, grasses, fish, small mammals, and carrion. Brown Bears are known for their ability to hibernate during winter months, utilizing their fat reserves for survival. The conservation status of Brown Bears varies depending on the subspecies and location, with some populations being more secure while others are threatened or endangered. Conservation efforts aim to protect their habitats, manage human-bear conflicts, and ensure the long-term survival of these magnificent creatures.', 80, 600, '2023-06-19 00:15:36'),
(11, 9, 'Goliath Birdeater', 'Theraphosa blondi', 'Arthropod', 'South America', 'Rainforest', 'Not evaluated', 'The Goliath Birdeater (Theraphosa blondi) is an impressive and renowned species of spider that resides in South America, particularly in the rainforests of the Amazon Basin. As the largest spider in the world by mass, it has earned its fearsome reputation. While its name might suggest it preys on birds, it typically consumes insects, other spiders, and small vertebrates. The Goliath Birdeater possesses powerful fangs and can deliver a painful bite, but it is generally docile unless provoked. With a leg span of up to 30 centimeters (12 inches) and covered in dense, brown hairs, it is a remarkable arthropod that captures the curiosity of arachnid enthusiasts worldwide.', 1, 2, '2023-06-19 00:25:49'),
(12, 10, 'Arctic Hare', 'Lepus arcticus', 'Mammal', 'Circumpolar', 'Arctic tundra', 'Least Concern', 'The Arctic Hare (Lepus arcticus) is a fascinating mammal that is well-adapted to the harsh Arctic tundra environments it inhabits. These hares have a thick, dense coat that changes color seasonally, providing excellent camouflage. In the winter, their fur is white to blend with the snowy landscape, while in the summer, it turns brown or grayish-brown to match the tundra vegetation. They have long hind legs, enabling them to move quickly and efficiently over the snow-covered terrain. Arctic Hares feed on a variety of plant materials, including grasses, mosses, and woody shrubs. They are also known for their ability to dig burrows in the snow for shelter. As a species, the Arctic Hare is currently classified as Least Concern on the conservation status scale, indicating that their population is stable and not at immediate risk.', 3, 5, '2023-06-19 00:29:01'),
(13, 11, 'Leopard Frog', 'Lithobates amurensis', 'Amphibian', 'Asia', 'Taiga', 'Critically Endangered', 'The Leopard Frog (Lithobates amurensis) is an amphibian species that inhabits the taiga region of Russia and Northeast Asia. These frogs are adapted to the cold temperate climate of the taiga, characterized by long winters and short summers. They have a semi-aquatic lifestyle, spending their time in wetlands, ponds, and slow-moving streams. The Amur Leopard Frog is critically endangered due to habitat loss, degradation of wetland habitats, pollution, and the introduction of non-native species. Conservation efforts are focused on protecting and restoring its habitat, as well as captive breeding programs to boost population numbers. The Amur Leopard Frog is a vital part of the taiga ecosystem, and preserving its population is crucial for maintaining biodiversity in the region.', 1, 2, '2023-06-19 00:34:10'),
(14, 12, 'Fennec Fox', 'Vulpes zerda', 'Mammal', 'Africa', 'Desert', 'Least Concern', 'The Fennec Fox (Vulpes zerda) is a remarkable mammal that is uniquely adapted to desert environments, particularly the Sahara Desert in North Africa. It is known for its distinct features, including large ears that help dissipate heat and detect prey underground, and a creamy, sandy-colored fur that provides camouflage. Fennec Foxes are nocturnal, spending the scorching desert days in cool burrows they dig in the sand. They have a diet that includes insects, small mammals, and desert vegetation. Their remarkable adaptations enable them to survive in the extreme desert climate, including conserving water and withstanding high temperatures. Fennec Foxes are currently classified as Least Concern on the conservation status scale, indicating that their population is relatively stable.', 1, 2, '2023-06-19 00:40:52'),
(15, 13, 'Grevy\'s Zebra', 'Equus grevyi', 'Mammal', 'Africa', 'Desert', 'Vulnerable', 'The Grevy\'s Zebra (Equus grevyi) is a majestic mammal found in the arid and semi-arid regions of Eastern Africa. It is known for its unique appearance, characterized by large ears, a tall and slender build, and striking black and white stripes that extend to the hooves. Grevy\'s Zebras inhabit desert and semi-desert landscapes where water availability is limited. They have adapted to these challenging conditions by being able to survive on sparse vegetation and by traveling long distances in search of water sources. Unfortunately, Grevy\'s Zebras are currently classified as Vulnerable due to habitat loss, competition with livestock for resources, and poaching for their skins and meat. Conservation efforts are focused on protecting their habitats, managing grazing areas, and raising awareness about their importance in the ecosystem.', 350, 450, '2023-06-19 00:45:42'),
(16, 14, 'Pirarucu', 'Arapaima gigas', 'Fish', 'South America', 'Rainforest', 'Vulnerable', 'The Pirarucu, also known as Arapaima, is an impressive fish species that inhabits the tropical rainforests of the Amazon Basin. It is known for its large size, robust body, and unique ability to breathe air. The Pirarucu has a sleek, elongated shape and can reach extraordinary lengths. It is considered one of the largest freshwater fish in the world. These fish have adapted to the flooded forests and slow-moving rivers of the Amazon, using their lung-like organ to extract oxygen from the air when water levels are low or oxygen is scarce. Unfortunately, due to overfishing and habitat degradation, the Pirarucu is listed as Vulnerable on the conservation status scale. Conservation efforts include sustainable fishing practices, protected areas, and community involvement to ensure the long-term survival of this remarkable species.', 60, 200, '2023-06-19 00:55:00'),
(17, 15, 'Emperor Penguin', 'Aptenodytes forsteri', 'Bird', 'Antarctica', 'Arctic tundra', 'Near Threatened', 'The Emperor Penguin (Aptenodytes forsteri) is an iconic bird species that is uniquely adapted to survive in the extreme conditions of Antarctica. These penguins are known for their large size and distinctive black and white plumage. They have a remarkable ability to withstand the harsh Antarctic climate, enduring long, cold winters and braving icy winds. Emperor Penguins breed on the sea ice and form large colonies, with males incubating their eggs in a specialized brood pouch while females go out to sea to feed. They feed on fish and other small marine creatures. Despite their ability to survive in Antarctica, Emperor Penguins are classified as Near Threatened due to the potential impacts of climate change and the reduction of sea ice, which affects their breeding and foraging patterns. Conservation efforts aim to protect their habitats and monitor their populations to ensure their long-term survival.', 22, 45, '2023-06-19 00:58:51'),
(18, 16, 'Musk Ox', 'Ovibos moschatus', 'Mammal', 'North America', 'Arctic tundra', 'Least Concern', 'The Musk Ox (Ovibos moschatus) is a fascinating mammal that thrives in the frigid Arctic tundra regions. It is recognized for its stocky build, shaggy coat, and formidable curved horns. Musk Oxen have adapted to the harsh tundra climate, with a dense undercoat that provides insulation and protection against extreme cold. They graze on tundra vegetation, such as grasses, sedges, and lichens. These animals are highly social and form herds, relying on group defense strategies against predators. Despite their resilient nature, Musk Oxen faced significant population decline in the past due to overhunting. However, conservation efforts have led to their recovery, and they are currently classified as Least Concern on the conservation status scale.', 200, 400, '2023-06-19 04:48:13'),
(19, 17, 'Reindeer', 'Rangifer tarandus', 'Mammal', 'North America', 'Tundra', 'Least Concern', 'The Reindeer, also known as Caribou, is a remarkable mammal that inhabits the tundra regions of North America, Europe, and Asia. These majestic animals are famous for their migration patterns and impressive antlers. Reindeer have adapted to the challenging tundra climate, featuring a dense fur coat and specialized hooves for traversing snow and ice. They are herbivores, feeding on a variety of tundra vegetation, including grasses, mosses, lichens, and shrubs. Reindeer are highly social animals and form large herds. They undertake long-distance migrations, covering vast distances in search of food and suitable habitats. Reindeer have significant cultural and ecological importance in the regions they inhabit. Currently, they are classified as Least Concern on the conservation status scale, indicating stable populations.', 60, 180, '2023-06-19 04:51:32'),
(20, 18, 'Bear Caterpillar', 'Gynaephora groenlandica', 'Arthropod', 'North America', 'Tundra', 'Not evaluated', 'The Arctic Woolly Bear Caterpillar (Gynaephora groenlandica) is a unique arthropod species that inhabits the cold tundra regions of the Arctic and subarctic. These caterpillars are known for their woolly appearance, featuring long hairs that provide insulation against the extreme cold. They are adapted to the tundra climate, where temperatures can be extremely low for much of the year. Arctic Woolly Bear Caterpillars feed on tundra vegetation, such as dwarf willows and other low-growing plants. They undergo several stages of development before transforming into adult moths. While they are not typically evaluated for conservation status individually, their presence in the tundra ecosystem contributes to the overall biodiversity and functioning of the region.', 1, 2, '2023-06-19 04:55:58'),
(21, 19, 'Giant Salamander', 'Andrias davidianus', 'Amphibian', 'Asia', 'Temperate', 'Critically Endangered', 'The Giant Salamander (Andrias davidianus) is a remarkable amphibian known for its impressive size and unique appearance. It is one of the largest amphibians in the world. These salamanders have a flattened body, a broad head, and distinct wrinkled skin. They are primarily aquatic, inhabiting rocky mountain streams and lakes in China. Chinese Giant Salamanders are nocturnal and feed on a variety of prey, including fish, crustaceans, and amphibians. Unfortunately, they are critically endangered due to habitat loss, water pollution, and overhunting. Conservation efforts are underway to protect their habitats, establish breeding programs, and raise awareness about their ecological importance. Preserving the Chinese Giant Salamander is crucial for maintaining the biodiversity and health of freshwater ecosystems in China.', 25, 60, '2023-06-19 05:00:59'),
(22, 20, 'Australian Magpie', 'Cracticus tibicen', 'Bird', 'Australia', 'Temperate', 'Least Concern', 'The Australian Magpie (Cracticus tibicen) is a striking bird species native to Australia. Despite its name, it is not closely related to the European magpie. Australian Magpies have a black and white plumage, with distinct white markings on their wings and back. They are known for their melodious and complex songs, often heard throughout urban and rural areas. These birds are highly adaptable and can be found in a variety of habitats, including forests, woodlands, parks, and urban areas. They have a diverse diet, feeding on insects, small animals, fruits, and seeds. Australian Magpies are intelligent and social birds, often forming close-knit family groups. They are not considered endangered and are classified as Least Concern on the conservation status scale.', 1, 2, '2023-06-19 05:06:28'),
(23, 21, 'Sumatran Orangutan', 'Pongo abelii', 'Mammal', 'Asia', 'Rainforest', 'Critically Endangered', 'The Sumatran Orangutan (Pongo abelii) is a critically endangered mammal and one of the two species of orangutans found in the world. They are native to the island of Sumatra in Indonesia. These orangutans have long reddish-brown hair and distinctive cheek pads in males. They spend most of their lives in the trees of the tropical rainforest, using their strong arms and flexible bodies to move through the canopy. Sumatran Orangutans are primarily herbivorous, feeding on fruits, leaves, and bark. They are highly intelligent and have complex social behaviors. Unfortunately, habitat loss due to deforestation, as well as poaching, are significant threats to their survival. Conservation efforts aim to protect their remaining habitats, establish wildlife corridors, and combat illegal hunting to secure the future of this critically endangered species.', 40, 90, '2023-06-19 05:10:10'),
(24, 22, 'Weddell Seal', 'Leptonychotes weddellii', 'Mammal', 'Antarctica', 'Arctic tundra', 'Least Concern', 'The Weddell Seal (Leptonychotes weddellii) is a fascinating mammal that inhabits the Antarctic and sub-Antarctic regions, particularly the Weddell Sea. These seals have a stocky body, with a mottled gray or brown coat that blends in with the icy environment. They are known for their remarkable diving abilities, capable of reaching impressive depths and staying submerged for extended periods. Weddell Seals primarily feed on fish and squid, often foraging under the sea ice. They have specialized adaptations such as a streamlined body shape and the ability to close their nostrils to prevent water entry during dives. Despite the challenges posed by the harsh Antarctic environment, Weddell Seals have a stable population and are currently classified as Least Concern on the conservation status scale.', 400, 1200, '2023-06-19 05:21:08'),
(25, 23, 'Scarlet Macaw', 'Ara macao', 'Bird', 'South America', 'Rainforest', 'Least Concern', 'The Scarlet Macaw (Ara macao) is a stunning and iconic bird known for its vibrant and colorful plumage. It has a striking combination of red, blue, yellow, and green feathers, with a large wingspan and a long, elegant tail. Scarlet Macaws are highly social and intelligent birds, often found in pairs or small flocks. They are primarily found in the tropical rainforests of Central and South America, including Brazil, where the city of Rio de Janeiro is located. These parrots have a strong beak and are known for their loud and distinctive calls. They feed on a variety of fruits, nuts, seeds, and even clay, which is an important source of minerals for their diet. While deforestation and illegal wildlife trade pose threats to their populations, Scarlet Macaws are currently classified as Least Concern on the conservation status scale, thanks to conservation efforts and protected areas that aim to preserve their habitats and combat illegal trade.', 1, 2, '2023-06-19 05:35:19');

--
-- Indexuri pentru tabele eliminate
--

--
-- Indexuri pentru tabele `animals`
--
ALTER TABLE `animals`
  ADD PRIMARY KEY (`id`),
  ADD KEY `animalid` (`animalid`),
  ADD KEY `name` (`name`),
  ADD KEY `science_name` (`science_name`),
  ADD KEY `type` (`type`),
  ADD KEY `region` (`region`),
  ADD KEY `climate` (`climate`),
  ADD KEY `conservation_status` (`conservation_status`),
  ADD KEY `min_weight` (`min_weight`),
  ADD KEY `max_weight` (`max_weight`);

--
-- AUTO_INCREMENT pentru tabele eliminate
--

--
-- AUTO_INCREMENT pentru tabele `animals`
--
ALTER TABLE `animals`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
